# Generated by Django 3.2 on 2023-05-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailchimp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=150)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
