# Generated by Django 3.2 on 2023-05-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_courses_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(editable=False, max_length=40)),
                ('fname', models.CharField(max_length=60)),
                ('lname', models.CharField(max_length=60)),
                ('company', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('address3', models.CharField(max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('course_title', models.CharField(max_length=250)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Purchaseorderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('orderitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('purchase_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='purchase.purchase')),
            ],
        ),
    ]
