# Generated by Django 3.2 on 2023-05-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='original_basket',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
