# Generated by Django 3.2 on 2023-05-15 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('purchase', '0002_auto_20230514_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='user_dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='dashboard.userdashboard'),
        ),
    ]
