# Generated by Django 3.2 on 2023-05-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20230520_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='lname',
        ),
        migrations.AddField(
            model_name='purchase',
            name='fullname',
            field=models.CharField(default='', max_length=150),
        ),
    ]
