# Generated by Django 3.2 on 2023-05-24 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20230521_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='purchase_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='purchase.purchase'),
        ),
    ]
