# Generated by Django 3.2 on 2023-05-15 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_company', models.CharField(blank=True, max_length=200, null=True)),
                ('default_address1', models.CharField(blank=True, max_length=100, null=True)),
                ('default_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('default_address3', models.CharField(blank=True, max_length=100, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=50, null=True)),
                ('default_telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('default_email', models.EmailField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
