# Generated by Django 3.2 on 2023-04-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20230422_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
