# Generated by Django 3.2 on 2023-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20230423_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image_url',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
    ]
