# Generated by Django 3.2 on 2023-04-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
