# Generated by Django 3.2 on 2023-05-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name_plural': 'Basket'},
        ),
    ]
